version: "3"
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - 3050:80
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./db:/data/db
        ports:
            - 27017:27017
    client:
        build:
            dockerfile: Dockerfile
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - NUXT_HOST=0.0.0.0
            - NUXT_PORT=3000
    api:
        build:
            dockerfile: Dockerfile
            context: ./backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        depends_on: 
            - mongo
        ports: 
            - 5000:5000
                
        